#!/bin/sh
# X86_64 软路由首次启动个性化设置
# 说明：软路由无无线网卡，本脚本不做任何无线配置

#---------- 系统 ----------
uci -q batch <<-EOF
	set system.@system[0].hostname='X86_89'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].ttylogin='0'
	set system.@system[0].log_size='128'
	set system.@system[0].urandom_seed='0'
	delete system.ntp
	set system.ntp=timeserver
	set system.ntp.enabled='1'
	set system.ntp.enable_server='0'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='ntp.tuna.tsinghua.edu.cn'
	commit system
EOF

#---------- 网口 ----------
# 默认只有 eth0 是 LAN、eth1 是 WAN
# 这里把 eth2 eth3 也并进 LAN 桥，四口机就有三个 LAN 口
EXTRA_LAN="eth2 eth3"

. /lib/functions.sh

LAN_BRIDGE=""

find_lan_bridge() {
	local sec="$1"
	local name
	config_get name "$sec" name
	[ "$name" = "br-lan" ] && LAN_BRIDGE="$sec"
}

config_load network
config_foreach find_lan_bridge device

if [ -n "$LAN_BRIDGE" ]; then
	for PORT in $EXTRA_LAN; do
		# 已经在桥里就跳过，避免重复
		if uci -q get "network.$LAN_BRIDGE.ports" | grep -qw "$PORT"; then
			continue
		fi
		uci -q add_list "network.$LAN_BRIDGE.ports=$PORT"
	done
	uci -q commit network
fi

exit 0
